name: Deploy to S3 and invalidate cloudfront cache

on:
  push:
    branches:
      - main
env:
  BUCKET_NAME: glens-bucket
  AWS_REGION: us-east-1


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::220664688409:role/FrontEnd_CI_CD_Role
        aws-region: ${{ env.AWS_REGION }}

    - name: Sync files to S3
      run: |
        aws s3 sync ./website s3://${{ env.BUCKET_NAME }}/ --delete --exact-timestamps

    - name: Invalidate cloudfront cache
      run: |
        aws cloudfront create-invalidation \
        --distribution-id E17793S3F9RQ4O \
        --paths "/*"
